Incorporación de los statement "try", "catch" y "finally"
Patagonian-IUPA/try-catch pull request #5
Opened 2020-11-29 19:47 UTC by Arcaytus

Buenas tardes Eduardo, aquí subo el ejercicio realizado de manejo de errores.

2020-11-29 20:08 UTC, Arcaytus commented
Soy Manuel Martínez. Me olvide de aclarar eso jaja

2020-11-30 12:22 UTC, reduardo7 requested changes

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +try {
La declaración de la `function` no puede generar un error, por lo que no es necesario dejar dentro de un `try` & `catch` esta declaración.
```suggestion
```

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +try {
IDEM primer comentario.

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +try {
IDEM primer comentario.

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> + db.connect();
El `try & catch` debería contener todo el contenido de la `function`.
Esta línea, `db,connect`, es justamente la que puede fallar, y es la que quedó fuera del bloque `try` & `catch`.

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +   db.save(id, dato);
`db.save` quedó fuera del bloque `try & catch`

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +   db.close();
`db.close` quedó fuera del bloque `try & catch`

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +try {
IDEM primer comentario.

2020-11-30 12:22 UTC, reduardo7 commented on src/ejercicios.js
> +try {
IDEM primer comentario.

2020-11-30 15:02 UTC, Arcaytus commented
Muchas gracias por las correcciones. Ahí las agregué.

2020-11-30 15:06 UTC, reduardo7 commented
Muy bien! 👍

2020-11-30 15:06 UTC, closed without merging